jQuery(document).ready(function){(
  $(".design").click(function(){
    $("hide1").toggle();
  });
  $(".development").click(function(){
    $("hide2").toggle();
  });
  $(".product").click(function(){
    $("hide3").toggle();
  });
});
  
$("document").ready(function(){
  $(".design").click(
    function(){
      $(".hide1").show();
      $(".design").hide();
    }
  );
  $(".development").click(
    function(){
      $(".hide2").show();
      $(".development").hide();
    }
  );
  $(".product").click(
    function(){
      $(".hide3").show();
      $(".product").hide();
    }
  );
}
);